# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: door-sensor-data-request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='door-sensor-data-request.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x1e\x64oor-sensor-data-request.proto\")\n\x15\x44oorSensorDataRequest\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\tB(\n$org.crazycoder.door.service.protobufP\x01\x62\x06proto3')
)




_DOORSENSORDATAREQUEST = _descriptor.Descriptor(
  name='DoorSensorDataRequest',
  full_name='DoorSensorDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceId', full_name='DoorSensorDataRequest.deviceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['DoorSensorDataRequest'] = _DOORSENSORDATAREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DoorSensorDataRequest = _reflection.GeneratedProtocolMessageType('DoorSensorDataRequest', (_message.Message,), dict(
  DESCRIPTOR = _DOORSENSORDATAREQUEST,
  __module__ = 'door_sensor_data_request_pb2'
  # @@protoc_insertion_point(class_scope:DoorSensorDataRequest)
  ))
_sym_db.RegisterMessage(DoorSensorDataRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$org.crazycoder.door.service.protobufP\001'))
# @@protoc_insertion_point(module_scope)
