# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: door-sensor-data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='door-sensor-data.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x16\x64oor-sensor-data.proto\"N\n\x0e\x44oorSensorData\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x17\n\x06status\x18\x03 \x01(\x0e\x32\x07.Status* \n\x06Status\x12\n\n\x06OPENED\x10\x00\x12\n\n\x06\x43LOSED\x10\x01\x42(\n$org.crazycoder.door.service.protobufP\x01\x62\x06proto3')
)

_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OPENED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=106,
  serialized_end=138,
)
_sym_db.RegisterEnumDescriptor(_STATUS)

Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
OPENED = 0
CLOSED = 1



_DOORSENSORDATA = _descriptor.Descriptor(
  name='DoorSensorData',
  full_name='DoorSensorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceId', full_name='DoorSensorData.deviceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='DoorSensorData.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='DoorSensorData.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=104,
)

_DOORSENSORDATA.fields_by_name['status'].enum_type = _STATUS
DESCRIPTOR.message_types_by_name['DoorSensorData'] = _DOORSENSORDATA
DESCRIPTOR.enum_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DoorSensorData = _reflection.GeneratedProtocolMessageType('DoorSensorData', (_message.Message,), dict(
  DESCRIPTOR = _DOORSENSORDATA,
  __module__ = 'door_sensor_data_pb2'
  # @@protoc_insertion_point(class_scope:DoorSensorData)
  ))
_sym_db.RegisterMessage(DoorSensorData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$org.crazycoder.door.service.protobufP\001'))
# @@protoc_insertion_point(module_scope)
