# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temp-sensor-data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='temp-sensor-data.proto',
  package='model',
  syntax='proto3',
  serialized_pb=_b('\n\x16temp-sensor-data.proto\x12\x05model\"\x83\x01\n\x15TemperatureSensorData\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65viceId\x18\x02 \x01(\t\x12\x10\n\x08humidity\x18\x03 \x01(\x02\x12\x13\n\x0btemperature\x18\x04 \x01(\x02\x12\x11\n\theatIndex\x18\x05 \x01(\x02\x12\x0b\n\x03vcc\x18\x06 \x01(\x05\x62\x06proto3')
)




_TEMPERATURESENSORDATA = _descriptor.Descriptor(
  name='TemperatureSensorData',
  full_name='model.TemperatureSensorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='model.TemperatureSensorData.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deviceId', full_name='model.TemperatureSensorData.deviceId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='model.TemperatureSensorData.humidity', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='model.TemperatureSensorData.temperature', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heatIndex', full_name='model.TemperatureSensorData.heatIndex', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vcc', full_name='model.TemperatureSensorData.vcc', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=165,
)

DESCRIPTOR.message_types_by_name['TemperatureSensorData'] = _TEMPERATURESENSORDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TemperatureSensorData = _reflection.GeneratedProtocolMessageType('TemperatureSensorData', (_message.Message,), dict(
  DESCRIPTOR = _TEMPERATURESENSORDATA,
  __module__ = 'temp_sensor_data_pb2'
  # @@protoc_insertion_point(class_scope:model.TemperatureSensorData)
  ))
_sym_db.RegisterMessage(TemperatureSensorData)


# @@protoc_insertion_point(module_scope)
