version: '2.1'
services:
  messenger:
    image: adyach/mrbot-messenger:0.1
    volumes:
      - /tmp
    environment:
      PAGE_ACCESS_TOKEN: ${PAGE_ACCESS_TOKEN}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

  nginx:
    image: adyach/mrbot-nginx:0.1
    links:
     - messenger
     - door-service
     - temp-service
    ports:
     - "80:80"
     - "443:443"
    volumes_from:
     - messenger
    volumes:
     - /etc/letsencrypt:/etc/letsencrypt
     - /etc/ssl/certs:/etc/ssl/certs

  door-service:
    image: adyach/mrbot-door-service:d41cce1
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://door-service-mongo/test
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
     - door-service-mongo
     - messenger
     - rabbitmq

  door-service-mongo:
    image: mongo:3.4.3
    volumes:
     - /data/db
    ports:
      - "27017:27017"

  temp-service:
    image: adyach/mrbot-temp-service:0.1
    links:
     - messenger

  rabbitmq:
    image: adyach/mrbot-rabbitmq:0.1
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
