version: '2.1'
services:
  messenger:
    image: adyach/mrbot-messenger:0.8
    volumes:
      - /usr/local/messenger:/data/db
    environment:
      PAGE_ACCESS_TOKEN: ${PAGE_ACCESS_TOKEN}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

  nginx:
    image: adyach/mrbot-nginx:0.2
    links:
     - messenger
     - door-service
     - temp-service
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - /etc/letsencrypt:/etc/letsencrypt
     - /etc/ssl/certs:/etc/ssl/certs

  door-service:
    image: adyach/mrbot-door-service:0.3
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://door-service-mongo/test
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
     - door-service-mongo
     - messenger
     - rabbitmq

  door-service-mongo:
    image: mongo:3.4.3
    volumes:
     - /usr/local/door-service:/data/db

  temp-service:
    image: adyach/mrbot-temp-service:0.4
    environment:
      CASSANDRA_HOST: temp-service-cassandra
    links:
     - messenger
     - temp-service-cassandra

  temp-service-cassandra:
    image: adyach/mrbot-temp-service-cassandra:3.10
    volumes:
      - /usr/local/temp-service-cassandra:/var/lib/cassandra
    environment:
      MAX_HEAP_SIZE: 250M
      HEAP_NEWSIZE: 50M

  rabbitmq:
    image: adyach/mrbot-rabbitmq:0.1
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
