version: '2.1'
services:
  mrbot:
    build:
      context: ./messenger
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - /tmp
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: HhoeUg42
      RABBITMQ_PASSWORD: Hyu5&^*j37hjklsdfbhekqDW2332

  nginx:
    build:
      context: ./nginx
    links:
     - mrbot
     - door-service
     - temp-service
    ports:
     - "80:80"
     - "443:443"
    volumes_from:
     - mrbot

  door-service:
    build:
      context: ./door-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://door-service-mongo/test
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: HhoeUg42
      SPRING_RABBITMQ_PASSWORD: Hyu5&^*j37hjklsdfbhekqDW2332
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
     - door-service-mongo
     - mrbot
     - rabbitmq

  door-service-mongo:
    image: mongo:3.4.3
    volumes:
     - /data/db
    ports:
      - "27017:27017"

  temp-service:
    build:
      context: ./temp-service
    links:
     - mrbot

  rabbitmq:
    build:
      context: ./rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
