spring:
  data.mongo:
    uri: mongodb://localhost/test
  rabbitmq:
    username: HhoeUg42
    password: Hyu5&^*j37hjklsdfbhekqDW2332
    host: localhost
    port: 5672
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

door.service:
  queue: "door.service.state"
  topic: "door.service"
